### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by casudinlix** [aksioma/aksioma_1.0#7]
Dear Pak Edi,
untuk login dan password delfaultnya apa ya?
tks

**Comment by edisuwoto** [comment]
user = admin
password = admin

**Comment by deroey** [comment]
Assamualaikum

saya menggunakan xampp. Tampilan auth: user dan password sudah tampil. namun masukan data untuk user:admin dan password :admin --> user tidak terdaftar.

database telah saya restore dan setting config database telah dilakukan. mohon petunjuk apakah ada yg terlewat.?

Terima kasih. Wassamualaikum wr.wb.

**Comment by andriyantomuhammad8** [comment]
Dear Pak Edi,
untuk login dan password delfaultnya apa ya?
tks

user : admin
pass : admin

md5 nya ini apa ya ?

BFPAJAhhiwq+SKLkVzs75ZfOZ9UUj0g7sgAf6zpjbxaOIxm58Q/ai2djVLmq6jkJTDxJoUljWIjjNI5IBnapcw==

**Comment by andriyantomuhammad8** [comment]
dicoba user : admin, pass : admin tidak bisa masuk

**Comment by amnibena** [comment]
pastikan databse sudah dibuat, dan edit koneksi database di bmt-system>application>config>database.php

**Comment by zickkeen** [comment]
@edisuwoto user/password admin:admin ndak bisa.
Kalau dilihat dari komposisi enkripsinya sepertinya habis ada perubahan komposisi enkripsi.

**Comment by seribudinar** [comment]
@pandigresik 
mas bisa login admin/admin ?

**Comment by pandigresik** [comment]
> 
> 
> @pandigresik
> mas bisa login admin/admin ?

saya reset data passwordnya pada kolom password

**Comment by Sukron18** [comment]
aw8LGtGg7tVZv8DeOgxr2gUd7wf6N0t0WYZ5Nl2tA4fwYq6iVZDuJjyAJlNjgZG9D1iWa2tm5J1A+nLqlcs8Hg==

itu di mysql pakai keamanan apa ya namanya, saya coba md5 tidak bisa.
